FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY Backend/ApiGateway/ApiGateway.csproj ./ApiGateway/
RUN dotnet restore ./ApiGateway/ApiGateway.csproj

COPY Backend/ApiGateway/ ./ApiGateway/
WORKDIR /app/ApiGateway
RUN dotnet publish -c Debug -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/ApiGateway/out ./
EXPOSE 1337
ENV ASPNETCORE_HTTP_PORTS=1337
ENTRYPOINT ["dotnet", "ApiGateway.dll"]